[language-server.typescript-language-server]
command = "vtsls"
args = ["--stdio"]
config.hostInfo = "helix"

[language-server.typescript-language-server.config.vtsls]
autoUseWorkspaceTsdk = true
experimental.maxInlayHintLength = 43
experimental.completion.enableServerSideFuzzyMatch = true

[language-server.typescript-language-server.config.typescript]
inlayHints.enumMemberValues.enabled = true
inlayHints.functionLikeReturnTypes = true
inlayHints.parameterNames.enabled = "all"
inlayHints.parameterNames.suppressWhenArgumentMatchesName = true
inlayHints.parameterTypes.enabled = true
inlayHints.propertyDeclarationTypes.enabled = true
inlayHints.variableTypes.enabled = true
inlayHints.variableTypes.suppressWhenTypeMatchesName = true
preferences.importModuleSpecifier = "relative"
preferences.importModuleSpecifierEnding = "auto"
preferences.quoteStyle = "single"
preferences.useAliasesForRenames = false
suggest.completeFunctionCalls = true
tsserver.maxTsServerMemory = 8192
updateImportsOnFileMove.enabled = "always"

[language-server.vscode-eslint-language-server.config]
format = true
validate = "on"
experimental = { useFlatConfig = false }
rulesCustomizations = []
run = "onType"
problems = { shortenToSingleLine = false }
nodePath = ""
codeAction = { disableRuleComment = { enable = true, location = "separateLine" } }
workingDirectory = { mode = "auto" }

[language-server.postgres-language-server]
command = "postgres-language-server_x86_64-unknown-linux-gnu"
args = [ "lsp-proxy" ]

[[language]]
name = "typescript"
language-servers = [
  { except-features = ["format"], name = "typescript-language-server" },
  "vscode-eslint-language-server",
]

[[language]]
name = "tsx"
language-servers = [
  { except-features = ["format"], name = "typescript-language-server" },
  "vscode-eslint-language-server",
]

[[language]]
name = "sql"
language-servers = ["postgres-language-server"]
file-types = ["sql"]
